// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaF8ou16-Z5fBevIUnffucjZA46Y6NlQk',
    appId: '1:941538334160:web:e4f801fe49f381576e95d5',
    messagingSenderId: '941538334160',
    projectId: 'flashchatflutterapp-558f8',
    authDomain: 'flashchatflutterapp-558f8.firebaseapp.com',
    storageBucket: 'flashchatflutterapp-558f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ3zFJ6vqVZU4ciSsLTA00kBxGpmMeMq4',
    appId: '1:941538334160:android:082f9ffe746fcef26e95d5',
    messagingSenderId: '941538334160',
    projectId: 'flashchatflutterapp-558f8',
    storageBucket: 'flashchatflutterapp-558f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiWEPov9DY0ERfTycPHE5b6BaHH8CInFE',
    appId: '1:941538334160:ios:b6f0e7cba2bc73c26e95d5',
    messagingSenderId: '941538334160',
    projectId: 'flashchatflutterapp-558f8',
    storageBucket: 'flashchatflutterapp-558f8.appspot.com',
    iosClientId: '941538334160-m6bal006v9517emm46n6mfsoqro6t0cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiWEPov9DY0ERfTycPHE5b6BaHH8CInFE',
    appId: '1:941538334160:ios:b6f0e7cba2bc73c26e95d5',
    messagingSenderId: '941538334160',
    projectId: 'flashchatflutterapp-558f8',
    storageBucket: 'flashchatflutterapp-558f8.appspot.com',
    iosClientId: '941538334160-m6bal006v9517emm46n6mfsoqro6t0cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
